package model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity (name = "usuario")
@Table(uniqueConstraints=@UniqueConstraint(columnNames = {"usuario", "senha"}))
@NamedQuery(name="Usuario.findByUsuario", query="SELECT u FROM usuario AS u "+
        "WHERE u.usuario = :usuario AND u.senha = :senha AND u.ativo = true") 
public class Usuario implements Serializable {
    @Id
    @GeneratedValue
    private int codigo;
    
    @Column(nullable = false)
    private String nome;
    
    @Column(length = 10, nullable = false)
    private String usuario;
    
    @Column(length = 10, nullable = false)
    private String senha;
    
    @Column(nullable = false)
    private boolean ativo = true;

    public Usuario() {
    }

   public Usuario(String nome, String usuario, String senha) {
       this.nome = nome;
       this.usuario = usuario;
       this.senha = senha;
   }
	
    public Usuario(int codigo, String nome, String usuario, String senha, boolean ativo) {
        this.codigo = codigo;
        this.nome = nome;
        this.usuario = usuario;
        this.senha = senha;
        this.ativo = ativo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
}


